### ISSUE TITLE
Missing backticks...

### ISSUE THREAD

**Issue by brandonhill** [betaflight/docker-betaflight-build#3]
Hi there. The snippet with options at the bottom of https://hub.docker.com/r/mikeller/betaflight-build/ is missing the backticks around `pwd`:
```
docker run -e "<parameter>=value" --rm -ti -vpwd:/opt/betaflight betaflight/betaflight-build
```

**Comment by mikeller** [comment]
Yes, you are correct, thank you very much for reporting this.

However, https://hub.docker.com/r/mikeller/betaflight-build/ is unmaintained, since this is now an official Betaflight project: https://hub.docker.com/r/betaflight/betaflight-build/

I will add a notice to indicate this to the top of https://hub.docker.com/r/mikeller/betaflight-build/.

**Comment by mikeller** [comment]
Notice done, please confirm.

**Comment by BRadFPV** [comment]
Running on OS X and needed backticks around `pwd`:
